### ISSUE TITLE
Separation motor plumes are not expanded at altitude.

### ISSUE THREAD

**Issue by JacobB094** [KochieBR/Avalanche-Plumes#2]
In RSMP, separation motors in vacuum had a realistic, wispy plume that was mostly visible as sparks and heat distortion. Could a similar effect be implemented here? The current blowtorch-like exhaust is a very big step down.

**Comment by KochieBR** [comment]
the heat distortion in vaccum was not realistic 
and the separator plumes are indeed designed to not expand at altitude to allow for retro motors on modded parts to not be clipped in and the blowtorch-like exaust is what small motors tend to look like i will experiment with switching to volumetric plumes in the future 
https://www.youtube.com/watch?v=MQFTWJPkvhE

**Comment by JacobB094** [comment]
You might have noticed this video is rather deep in the atmosphere. You want to see an ullage motor in hard vacuum, try this:
https://www.youtube.com/watch?v=xMr_AGJprrg
Truth to be told, it does not resemble RSMP's wispy approach either, though it'd be appropriate for very small motors. SSRB separation videos also show the exhaust gas is very orange even at high altitude, but also very expanded. The blowtorch is only a thing down low.

The "heat distortion" was somewhat overdone, but the principle of it is very much realistic - it comes from differences in coefficient of refraction between area where the gas is, and the area where it isn't. 
https://childrenofadeadearth.wordpress.com/2016/04/11/why-does-it-look-like-that-part-1/
Scroll down to the second part. Here is a well explained look at why rocket plumes in space look the way they do (they're not overly detailed in CoADE, but it focuses or NTRs). Note, actual plumes, including in the Saturn video, appear to curve slightly outward in vacuum. This is because there's still some pressure within the plume, so the molecules comprising it accelerate away from each other as the plume expands.

I never found plume clipping to be a big problem with wispy vacuum plumes. Removing expansion is a very bad decision IMO. I actually spent some time troubleshooting, convinced that something was broken in my install. After so long with every plume having it, it was quite jarring to see the new retro exhaust keep its sea level look in vacuum.

**Comment by KochieBR** [comment]
i stand by the opinion that ksp is a game and you shouldnt go 100% on realism and to do that you have to make compromises
plumes in ksp do not have the "heatdistortion" in any template and as i said it before the under expansion is to prevent plume from clipping into parts so i will not be changing it currently but im open to a possible extra plume that expands more on parts that dont need the under expansion
