### ISSUE TITLE
Compatibility issues between Avalanche Plumes v1.0.3 and BDB v1.13.0

### ISSUE THREAD

**Issue by Aebestach** [KochieBR/Avalanche-Plumes#4]
![image](https://github.com/user-attachments/assets/4ef1e437-6bde-4278-a819-1c7a009a3cd4)
[KSP.log](https://github.com/user-attachments/files/16601939/KSP.log)

Avalanche-Plumes[Version 1.0.3] and BDB[v1.13.0] have bugs

After my test, I found that when BDB and Avalanche Plumes are used together, B9 and warning problems will be reported. The log is shown above.

**Comment by KochieBR** [comment]
il revert the change that causes that
