### ISSUE TITLE
B9 warning for duplicate NEEDS tag: Titan_III_Booster_Nozzle_Patch

### ISSUE THREAD

**Issue by OrbitalManeuvers** [KochieBR/Avalanche-Plumes#5]
First line has two NEEDS[]

@PART[bluedog_UA120*]:NEEDS[Bluedog_DB]:NEEDS[Waterfall,Bluedog_DB,!zRealPlume]:AFTER[Bluedog_DB]

p.s. THANK YOU for working on this mod - it's really fantastic. I use it in all my installs now \o/

**Comment by KochieBR** [comment]
already fixed ty for notifying me
