### ISSUE TITLE
SRB flame doesn't turn off

### ISSUE THREAD

**Issue by Dynhus** [KochieBR/Avalanche-Plumes#6]
Hi! When srb is out of fuel, his flame doesn't disappears, it's only visual. When i uninstall Avalanche only (and not it's dependencies), it works correctly. I also tried uninstall/reinstall all dependencies with Avalanche, it doesn't solve the problem.

Do you know what can cause that?

**Comment by KochieBR** [comment]
the plume does have a "burnout" effect that makes the plume stay for a bit after it runs out of fuel

**Comment by Dynhus** [comment]
Oh you right! I just tested it. But this burnout effect lasts 1 minute, it's normal?

**Comment by KochieBR** [comment]
thats on the longer end but it has a buffer of around 20s for most srbs

**Comment by Dynhus** [comment]
Thanks for informations! I'm not fan of burnout effect, so I tried to change in files "eventDuration = 60" for "0", and it's seem to works.
Thanks again for your time, and your good mod!

**Comment by KochieBR** [comment]
glad to help
